### ISSUE TITLE
Polish Movement Systems

### ISSUE THREAD

**Issue by Tmac4930** [luke-goldfain/Hangtime#34] opened 2019-09-21 14:58 UTC
Based on the feedback given though playtesting, we have some changes to the movement system that should be considered and implemented for testing.

**Comment by luke-goldfain** [comment] 2019-09-23 07:14
Can you share your feedback somewhere @Tmac4930 ? Right now I only have Eric's to go off of.

**Comment by Tmac4930** [comment] 2019-09-25 02:28
Feedback is in the documentation section of our Google drive in the hangtime folder. I made a complete list of with Eric's 11 first and my 9 plus David's feedback is also listed.

**Comment by luke-goldfain** [comment] 2019-09-25 04:42
> Feedback is in the documentation section of our Google drive in the hangtime folder. I made a complete list of notes with Eric's 11 first and my 9 plus David's feedback is also listed.

Thanks, I'll take a look at it.

**Comment by luke-goldfain** [comment] 2019-09-25 05:09
Clear needs based off of feedback:

- Clarity about grapplability length: Distance indicator below reticle
- More feedback when grappling: Grapple "travel time" and visual (already implemented)
- A way to prevent hanging in mid-air for too long: More effective fast-fall with feedback
- A way to prevent clipping through the stage: A 3D-modeled terrain rather than the Unity terrain we currently have (@kdf32 should be working on this already)
- Less blandness, more visual interest in the environment: See previous point
- Immediate clarity concerning the objective of the game: HUD waypoints and a countdown timer
- Visual communication to the player that they have already hit a checkpoint: Color change and light pillar disappearing
- More clarity on the checkpoint meter: A programmable segmented meter, and possibly a flag at the top (polish)
- Visual feedback for switching between swinging and pulling: A UI element akin to a crouch indicator in an FPS
- A skybox! (Artists?)

Other feedback to consider:

- Mid-air jumps shouldn't kill your momentum. This was intended as the initial point of jumping in mid-air was to trade off momentum for resituating yourself, so the repeated complaint about it is interesting.
- Jumping and running feels "sticky" and as though the player is pulled towards surfaces. This was stated multiple times but it's really abstract and hard to pinpoint. There is nothing to back it up as far as programming goes.
- Running feels bad. Most variables involving run speed and momentum are editable in inspector, so this should be easy to play around with.
- Movement feels "robotic". This could be assuaged with camera-shake and more playing with momentum, as well as sounds.

**Comment by luke-goldfain** [comment] 2019-09-25 05:10
Thoughts @Tmac4930 ? Anything you would add to this?

**Comment by Tmac4930** [comment] 2019-09-25 12:41
Most of the feedback to consider section could be looked at in a different light. 

-  Double jump killing momentum: Although it was a intentional aspect of the design playtesting has shown that some players don't like it. So maybe we should re-examine our core design goals and determine if the gameplay needs this feature in it's current state. And personally I'm unsure here if a change NEEDS to be made.
-  sticky jumping and running: I've personally pointed this out before in my own experiences with the game. It's definitely hard to pinpoint because the issue is inconsistent and mostly dependent on how you attempt to play the game. I've noticed that it's only noticable when trying to run and jump by foot in tight spaces like on the mountain path. If I was to venture a guess I would say it's probably a side effect of the wall sticking feature we put in during our prototyping phase. 
- I'll see if I can experiment with different run speeds and settings
- This has a wide array of fixes I think. I'd like to avoid shaking the camera but a clear fix would be to make transitions between speeds more realistic. Their is to much sudden stopping, it should feel as though the player is

**Comment by dantogno** [comment] 2019-09-25 15:53
My advice is get the feedback in and then test more. The game might be fun with the current movement mechanics, and it's not really worth spending a bunch of time changing things if it's already fun. I think the lack of clarity and objective for the player are the main things blocking fun so far.

**Comment by luke-goldfain** [comment] 2019-09-25 16:48
> Most of the feedback to consider section could be looked at in a different light.

For clarity's sake, I'd like to mention that everything I put in the "Feedback to consider" section is stuff I'm not totally sure about. Also, the first sentence of each is meant to be the feedback, followed by my thoughts on it. It might have been better to format it this way:

> "Mid-air jumps shouldn't kill your momentum" - This was intended as the initial point of jumping in mid-air was to trade off momentum for resituating yourself, so the repeated complaint about it is interesting.

I agree with most of what you said about that section @Tmac4930 . And good point @dantogno , I'd like to prioritize putting everything else in that we have planned before coming back to this and seeing what's still true.

**Comment by Tmac4930** [comment] 2019-09-25 16:53
Yeah sounds good, after all of the feedback mechanics and gameplay loop is fully established for the alpha build we can run another set of playtesting. Following that, we can confirm what needs to be polished.

**Comment by luke-goldfain** [comment] 2019-10-11 02:10
I opened and moved around some more specific issues regarding movement systems, so for now I'm moving this issue into "ready for review". Any specific concerns with the movement system from here on out might be better suited to individual issues.

**Closed by luke-goldfain** 2019-10-11 02:10 UTC
